"""Update model relationships

Revision ID: fbf798e55d3b
Revises: 40a5b4d05728
Create Date: 2025-04-03 11:12:24.542424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf798e55d3b'
down_revision = '40a5b4d05728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.alter_column('artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
